version: '3.1'

services:
  go_app:
    build:
      context: .
    container_name: go_app
    ports:
      - 8080:8000
    volumes:
      - .:/go/src/github.com/app/go_watcher
    working_dir: /go/src/github.com/app/go_watcher
  psql:
    image: postgres
    restart: always
    container_name: psql
    volumes:
      - ./.docker/psql:/var/lib/postgresql/data/
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}