version: '3.1'

services:
  go_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: shortener_app
    tty: true
    ports:
      - 8080:8000
    depends_on:
      psql:
        condition: service_healthy


  psql:
    image: postgres:13.6-alpine3.15
    restart: always
    container_name: psql
    volumes:
      - ./.docker/psql:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}